services:
  php-fpm:
    build:
      context: .
      dockerfile: Dockerfile
    image: php:8.2-fpm
    container_name: books_catalog_php_fpm
    restart: unless-stopped
    working_dir: /var/www
    volumes:
      - .:/var/www
    networks:
      - app_network

  web:
    image: nginx:alpine
    container_name: books_catalog_web
    restart: unless-stopped
    ports:
      - "${NGINX_HOST}:80"
    volumes:
      - .:/var/www
      - ./nginx.conf:/etc/nginx/conf.d/default.conf
    networks:
      - app_network

  db:
    image: postgres:13
    container_name: books_catalog_db
    restart: unless-stopped
    environment:
      POSTGRES_USER: ${COMMAND_DATABASE_USER}
      POSTGRES_PASSWORD: ${COMMAND_DATABASE_PASSWORD}
      POSTGRES_DB: ${COMMAND_DATABASE_NAME}
    ports:
      - "${COMMAND_DATABASE_PORT}:5432"
    networks:
      - app_network

networks:
  app_network:
    driver: bridge
